DECLARE
  ENQUEUE_OPTIONS DBMS_AQ.ENQUEUE_OPTIONS_T;
  MESSAGE_PROPERTIES DBMS_AQ.MESSAGE_PROPERTIES_T;
  MESSAGE_HANDLE RAW(16);
  MESSAGE AQ_TYPE_BOOK;
BEGIN
  
  MESSAGE := AQ_TYPE_BOOK('JAVA 8', 
          'THIS BOOK ABOUT NEW JAVA VERSION, JAVA 8', 
          2016);
  ENQUEUE_OPTIONS.VISIBILITY := DBMS_AQ.ON_COMMIT;
  ENQUEUE_OPTIONS.SEQUENCE_DEVIATION := NULL;
  MESSAGE_PROPERTIES.EXPIRATION := DBMS_AQ.NEVER;
  
  DBMS_AQ.ENQUEUE(
    QUEUE_NAME => 'MSG_BOOK',
    ENQUEUE_OPTIONS => ENQUEUE_OPTIONS,
    MESSAGE_PROPERTIES => MESSAGE_PROPERTIES,
    PAYLOAD => MESSAGE,
    MSGID => MESSAGE_HANDLE
  );
  
  COMMIT;
  
END;

SELECT COUNT(*) FROM AQ$T_AQ_BOOKS;
SELECT USER_DATA FROM AQ$T_AQ_BOOKS;