DROP USER AQADM_USER CASCADE;

CREATE USER AQADM_USER IDENTIFIED BY AQADM_USER;
GRANT CREATE SESSION, CONNECT, RESOURCE, 
      AQ_ADMINISTRATOR_ROLE, AQ_USER_ROLE TO AQADM_USER;
GRANT EXECUTE ON DBMS_AQADM TO AQADM_USER;
GRANT EXECUTE ON DBMS_AQ TO AQADM_USER;

ALTER USER AQADM_USER QUOTA 100 M ON USERS;