SET SERVEROUTPUT ON;
DECLARE
  L_VAR INTEGER := 17.5;
  SUBTYPE MYINT IS NUMBER(38, 0);
  L_MYINT MYINT := 19.5;
  
  SUBTYPE MYINT_NN IS NUMBER(38, 0) NOT NULL;
  L_MYINT_NN MYINT_NN := 19;--IF COMMENT, THEN NEXT LINE(10 LINE) WILL BE ERROR
BEGIN
  DBMS_OUTPUT.PUT_LINE('L_MYINT_NN = ' || L_MYINT_NN); --a variable declared NOT NULL must have an initialization assignment

  DBMS_OUTPUT.PUT_LINE('L_VAR = ' || L_VAR);
  DBMS_OUTPUT.PUT_LINE('L_MYINT = ' || L_MYINT);
  L_MYINT := NULL;
  DBMS_OUTPUT.PUT_LINE('L_MYINT = ' || L_MYINT);
  IF L_MYINT IS NULL THEN 
    DBMS_OUTPUT.PUT_LINE('L_MYINT IS NULL');
  END IF;
  -----------------
  
END;