SET SERVEROUTPUT ON;
<<PARENT>>
DECLARE
  L_VAR NUMBER;
  L_VAR_COMMON NUMBER;
BEGIN
  L_VAR := 1;
  L_VAR_COMMON := 1;
  DBMS_OUTPUT.PUT_LINE('L_VAR = ' || L_VAR);
  DBMS_OUTPUT.PUT_LINE('L_VAR_COMMON = ' || L_VAR_COMMON);
  ---------------------------
  DECLARE
    L_VAR NUMBER := 9;
  BEGIN
    L_VAR_COMMON := 9;
    
    DBMS_OUTPUT.PUT_LINE('IN L_VAR = ' || L_VAR);
    DBMS_OUTPUT.PUT_LINE('IN L_VAR_COMMON = ' || L_VAR_COMMON);
    PARENT.L_VAR := 10;
    DBMS_OUTPUT.PUT_LINE('IN PARENT.L_VAR = ' || PARENT.L_VAR);
  END;
  ---------------------------
  DBMS_OUTPUT.PUT_LINE('L_VAR = ' || L_VAR);
  DBMS_OUTPUT.PUT_LINE('L_VAR_COMMON = ' || L_VAR_COMMON);
END;