PROMPT THIS IS PROMPT OPERATION;

SELECT *
FROM DBA_USERS U
WHERE U.USERNAME = '&USERNAME';

SELECT *
FROM DBA_USERS U
WHERE U.USER_ID = &USER_ID;

SELECT *
FROM DBA_USERS U
WHERE U.USER_ID = :USER_ID;